name: Provision Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install LocalStack CLI
        run: |
          pip install localstack
          export PATH=$PATH:~/.local/bin

      - name: Verify LocalStack Installation
        run: ~/.local/bin/localstack --version

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

  start-localstack:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Start LocalStack with Docker
        run: |
          export LAMBDA_EXECUTOR=docker
          ~/.local/bin/localstack start -d
        env:
          LAMBDA_EXECUTOR: docker

  build:
    runs-on: ubuntu-latest
    needs: start-localstack

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform