name: Provision Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install LocalStack CLI
        run: pip install localstack

      - name: Verify LocalStack Installation
        run: localstack --version

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

  start-localstack:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Start LocalStack with Docker
        run: |
          docker run --name localstack -d -p 4566:4566 -e LAMBDA_EXECUTOR=docker localstack/localstack
        env:
          LAMBDA_EXECUTOR: docker

  init-terraform:
    runs-on: ubuntu-latest
    needs: start-localstack

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Terraform Init
        run: |
          terraform init -upgrade
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Verify Terraform Plugins
        run: terraform providers
        working-directory: ./terraform

  deploy:
    runs-on: ubuntu-latest
    needs: init-terraform

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Terraform Apply
        run: |
          terraform init -upgrade
          terraform apply -auto-approve
        working-directory: ./terraform